name: Build & Push

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - # https://github.com/marketplace/actions/docker-login
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        # https://github.com/marketplace/actions/build-and-push-docker-images
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: hagay3/github-actions-demo:${{ github.sha }}