name: Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VERSION: ${{ github.event.inputs.version }}
        run: |
            chmod u+x ./.github/scripts/deploy.sh
            ./.github/scripts/deploy.sh

      # https://github.com/marketplace/actions/slack-send-to-slack
      - name: Send slack message
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
             text: ":rocket: *Deployment Notice*\nA new version has just been deployed by *${{ github.actor }}*! :tada:"
             blocks:
                - type: "section"
                  text:
                    type: "mrkdwn"
                    text: ":rocket: *Deployment Notice*\nA new version has just been deployed by *${{ github.actor }}*! :tada:"
                - type: "section"
                  text:
                    type: "mrkdwn"
                    text: "*Status:* `${{ job.status }}`"
                - type: "section"
                  text:
                    type: "mrkdwn"
                    text: "*Version:* `${{ github.event.inputs.version }}`"
                - type: "section"
                  text:
                    type: "mrkdwn"
                    text: "<http://production-github-actions-demo.hagaiacademy.com:3000/volt-react-dashboard#/dashboard/overview|🚀 Go to Dashboard>"
